### ISSUE TITLE
Can't install, weird dependency to phonegap-plugin-push

### ISSUE THREAD

**Issue by eric-burel** [aporat/cordova-plugin-fetch#16]
Hi,
I added `cordova-plugin-fetch` to a meteor project, but it wont install. It fails with this error message:
```
 While adding plugin cordova-plugin-fetch@1.0.0 to Cordova project:              
   Uh oh!                                                                          
   "/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/plugins/cordova-plugin-fetch/src/android/com/adobe/phonegap/push/PushPlugin.java" not found!
   at copyFile (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/lib/pluginHandlers.js:219:36)
   at copyNewFile (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/lib/pluginHandlers.js:250:5)
   at install (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/lib/pluginHandlers.js:43:17)
   at ActionStack.process (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
   at PluginManager.doOperation (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
   at PluginManager.addPlugin (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
   at /home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/Api.js:254:18
   at _fulfilled (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:854:54)
   at self.promiseDispatch.done (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:883:30)
   at Promise.promise.promiseDispatch (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:816:13)
   at /home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:570:49
   at runSingle (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:137:13)
   at flush (/home/eric-burel/Websites/simply-charge/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:125:13)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
```

I don't understand because there is no dependency to this plugin, maybe it is loaded by some other lib ?

**Comment by fortinmike** [comment]
I'm experiencing the exact same thing. Did you find a solution, @eric-burel ?

**Comment by eric-burel** [comment]
Sorry I don't maintain this app anymore, but I think I've either changed the version of cordova-plugin-fetch or went using another lib. I think it was a versionning issue somehow.
